### ISSUE TITLE
Some API suggestions:)

### ISSUE THREAD

**Issue by He-Pin** [foldright/cffu#12]
Frist thanks for sharing, some suggestions below:

1. Provides an extension definition for Kotlin ?
2. Provides an extension for Vertx Function?
3. How about keep the Cffu a clean room, and not extends the `Future` and `CompletionStage` directly, but provides methods like `fromCompletionStage` and `toCompletionStage`.
4. then we can have method like `failed` instead of `failedStage`.

**Comment by oldratlee** [comment]
> * Provides an extension definition for `Kotlin` ?

Yes! `Kotlin` extension methods is amazing, a MUST have. 🎉


> * Provides an extension for Vertx Function?

`VertX` is another (full-fledged) concurrency framework.

Maybe keep cffu only concern `CompletableFuture`,
and be a tiny sidekick lib of `CompletableFuture` is ok.


> * How about keep the Cffu a clean room, and not extends the `Future` and `CompletionStage` directly, but provides methods like `fromCompletionStage` and `toCompletionStage`.

Good design idea!

The  that Cffu extends the `Future` and `CompletionStage` instead provides methods like `fromCompletionStage` and `toCompletionStage`,

**Comment by oldratlee** [comment]
@He-Pin 

this commit(66e06dcc5e5507261bf0a02419e13d75abc5956a) has added a `Kotlin extension method`:

```kt
public <T> Cffu<T> asCffu(CompletionStage<T> stage)
```

Any suggestions about `Kotlin extension methods` is welcome~ ❤️
