### ISSUE TITLE
Consider removing methods using common pool

### ISSUE THREAD

**Issue by linzee1** [foldright/cffu#213]
<img width="781" alt="image" src="https://github.com/user-attachments/assets/72efd0a6-0e7e-48a3-bcfc-10167560a292">

I saw some methods do not require user to pass executors.
It is often dangerous and error-prone to use common pool in Java. 
Why not remove methods that using common pool to avoid misuse?

[Wrong use case](https://juejin.cn/post/7165704556540755982)
[Dangerous use of ForkJoinPool](https://github.com/corona-warn-app/cwa-server/issues/399)

**Comment by XW512** [comment]
I think there are two ways to keep it convenient for users who don't have a lot of call volume to use. If they all need to define executors themselves, it would be too cumbersome

**Comment by oldratlee** [comment]
> I saw some methods do not require user to pass executors.
> It is often dangerous and error-prone to use common pool in Java.
> Why not remove methods that using common pool to avoid misuse?

`cffu` lib support the best practice and safe usage of executor by new classes:

- [`CffuFactory`](https://github.com/foldright/cffu/blob/main/cffu-core/src/main/java/io/foldright/cffu/CffuFactory.java)
- [`Cffu`](https://github.com/foldright/cffu/blob/main/cffu-core/src/main/java/io/foldright/cffu/Cffu.java)

support default executor setting, and must set.

------

[CompletableFutureUtils](https://github.com/foldright/cffu/blob/main/cffu-core/src/main/java/io/foldright/cffu/CompletableFutureUtils.java) is enhance the CompletableFuture and consist with it, or it will a surprise as a `util class`.
