### ISSUE TITLE
Replace temp incomplete CF with singleton

### ISSUE THREAD

**Issue by linzee1** [foldright/cffu#236]
<img width="712" alt="image" src="https://github.com/user-attachments/assets/d2747605-6971-4152-89a5-58ad49033ee9">

Methods like allResultsFastFailOf, allFastFailOf, anySuccessOf in CompletableFutureUtils use fill method.
The incomplete CF is only used in the scope of the method that call fill. Therefore it is safe to use singleton.
It maybe better to use static singleton instead of incomplete CF for the sake of efficiency and memory usage.
Also we should be aware of memory leaks.

**Comment by oldratlee** [comment]
### The static incomplete `CompletableFuture` instances cause **memory leak**.

## demo code

https://github.com/foldright/cffu/blob/6769bb77822571e0c857cc8899af82762916f006/cffu-core/src/test/java/io/foldright/demo/IncompleteCfMemoryLeakDemo.java#L16-L25

#### Output Sample(set `-Xmx256m -Xms256m` JVM option):

```java
start IncompleteCfMemoryLeakDemo
loop    0
loop   10
loop   20
loop   30
...
loop  220
loop  230
loop  240
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:501)
	at java.base/java.lang.invoke.DirectMethodHandle$Holder.newInvokeSpecial(DirectMethodHandle$Holder)
	at java.base/java.lang.invoke.Invokers$Holder.linkToTargetMethod(Invokers$Holder)
	at io.foldright.demo.IncompleteCfMemoryLeakDemo.main(IncompleteCfMemoryLeakDemo.java:22)
```

## best practice

It's best practice NOT to reuse (incomplete) `CompletableFuture` instances:

- less instance dependencies more GC friendly 🤖
- `CompletableFuture` instance creation is fairly cheap

## `cffu` optimization

do NOT reuse incomplete CF instance in method `CompletableFutureUtils#fill0`

- commit f15e887b34d2cfa3b573ac63bc914a12331a4da9 by @linzee1 💕
- released in [`v1.0.0-Alpha22`](https://github.com/foldright/cffu/releases/tag/v1.0.0-Alpha22)
