### ISSUE TITLE
Maven 下载失败

### ISSUE THREAD

**Issue by 1713612859** [foldright/cffu#249]
![image](https://github.com/user-attachments/assets/de0831a7-03e8-43de-8e3e-86000ccdcbdd)

**Comment by oldratlee** [comment]
@1713612859 maven中央库中有了：

https://central.sonatype.com/artifact/io.foldright/cffu/1.0.0-Alpha24/overview

可能和你的maven、IDE配置有关。

可以再试一下，

或是 用 mvn命令行 试试 先执行工程依赖下载

**Comment by 1713612859** [comment]
是否因为 用了阿里云镜像原因

**Comment by 1713612859** [comment]
目前下载还是会依赖爆红
