### ISSUE TITLE
CompletableFutureUtils的cffuOrTimeout(C cfThis, long timeout, TimeUnit unit)控制超时不准

### ISSUE THREAD

**Issue by XW512** [foldright/cffu#279]
hello，我使用cffu的CompletableFutureUtils的cffuOrTimeout方法控制时间超时，发现这个超时控制不准，我配置了超时时间是2900毫秒，但是发现超时时间是2970毫秒，不是2900毫秒就超时了，这个超时是不是单独控制的，我使用CompletableFuture控制超时是很准的

**Comment by oldratlee** [comment]
> hello，我使用cffu的CompletableFutureUtils的cffuOrTimeout方法控制时间超时，发现这个超时控制不准，我配置了超时时间是2900毫秒，但是发现超时时间是2970毫秒，不是2900毫秒就超时了，这个超时是不是单独控制的，我使用CompletableFuture控制超时是很准的

Hi @XW512，可以给一下示例代码及其运行结果。

我查一下

**Comment by XW512** [comment]
> > hello，我使用cffu的CompletableFutureUtils的cffuOrTimeout方法控制时间超时，发现这个超时控制不准，我配置了超时时间是2900毫秒，但是发现超时时间是2970毫秒，不是2900毫秒就超时了，这个超时是不是单独控制的，我使用CompletableFuture控制超时是很准的
> 
> Hi @XW512，可以给一下
> 
> * 示例代码及其对比运行结果
>   
>   * 可以提供成一个可运行的 repo 工程
>   * 这样有完整的信息，如使用的`cffu`版本、执行方式
> * 环境信息，如运行JDK版本
> 
> 我复现排查一下 💕
> 
> PS：
> 
> * 时长偏移一个可能的原因是首次执行，涉及如 类加载、线程池初始化/线程启动
> * 对于这样的情况，非首次执行，或说预热后，就好了

噢噢，有可能，也可能与我的环境有关，为了再次验证，昨天又进行再次的压测，发现CompletableFuture这个控制超时也出现误差，这个CompletionService的poll方法超时控制倒是控制很准确

**Comment by XW512** [comment]
> > hello，我使用cffu的CompletableFutureUtils的cffuOrTimeout方法控制时间超时，发现这个超时控制不准，我配置了超时时间是2900毫秒，但是发现超时时间是2970毫秒，不是2900毫秒就超时了，这个超时是不是单独控制的，我使用CompletableFuture控制超时是很准的
> 
> Hi @XW512，可以给一下
> 
> * 示例代码及其对比运行结果
>   
>   * 可以提供成一个可运行的 repo 工程
>   * 这样有完整的信息，如使用的`cffu`版本、执行方式
> * 环境信息，如运行JDK版本
> 
> 我复现排查一下 💕
> 
> PS：
> 
> * 时长偏移一个可能的原因是首次执行，涉及如 类加载、线程池初始化/线程启动
> * 对于这样的情况，非首次执行，或说预热后，就好了

我大概率猜测应该是线程池初始化的问题，我看下怎么设置线程池的取用规则

**Comment by XW512** [comment]
> > hello，我使用cffu的CompletableFutureUtils的cffuOrTimeout方法控制时间超时，发现这个超时控制不准，我配置了超时时间是2900毫秒，但是发现超时时间是2970毫秒，不是2900毫秒就超时了，这个超时是不是单独控制的，我使用CompletableFuture控制超时是很准的
> 
> Hi @XW512，可以给一下
> 
> * 示例代码及其对比运行结果
>   
>   * 可以提供成一个可运行的 repo 工程
>   * 这样有完整的信息，如使用的`cffu`版本、执行方式
> * 环境信息，如运行JDK版本
> 
> 我复现排查一下 💕
> 
> PS：
> 
> * 时长偏移一个可能的原因是首次执行，涉及如 类加载、线程池初始化/线程启动
> * 对于这样的情况，非首次执行，或说预热后，就好了

还有一个我想问下，CompletableFutureUtils.cffuOrTimeout这个方法的超时控制的线程，我看如果不配置的话，走的是默认defaultExecutor(cfThis)线程池，这个线程池应该是使用默认的ForkJoinPool.commonPool()，如果并发请求高的话，是不是可能会出现超时控制线程池不足的情况

**Comment by oldratlee** [comment]
> CompletableFutureUtils.cffuOrTimeout这个方法的超时控制的线程，我看如果不配置的话，走的是默认defaultExecutor(cfThis)线程池，这个线程池应该是使用默认的ForkJoinPool.commonPool()，如果并发请求高的话，是不是可能会出现超时控制线程池不足的情况

嗯嗯，是的。

当线程池占满时，自然影响超时的触发、任务的执行。
类似的，当系统负载飙高时，自然也影响。

**Comment by XW512** [comment]
> > CompletableFutureUtils.cffuOrTimeout这个方法的超时控制的线程，我看如果不配置的话，走的是默认defaultExecutor(cfThis)线程池，这个线程池应该是使用默认的ForkJoinPool.commonPool()，如果并发请求高的话，是不是可能会出现超时控制线程池不足的情况
> 
> 嗯嗯，是的。
> 
> 当线程池占满时，自然影响超时的触发、任务的执行。 类似的，当系统负载飙高时，自然也影响。

好的，我明白了，这个issue我关了哈

**Comment by oldratlee** [comment]
> 这个CompletionService的poll方法超时控制倒是控制很准确

对于`CompletionService`也可以对比测试（保持相同条件下），结果应该是区别不大；否则有值得看看排查。

**Comment by XW512** [comment]
> > 这个CompletionService的poll方法超时控制倒是控制很准确
> 
> @XW512 对于`CompletionService`也可以对比测试（保持相同条件下），结果应该没有明显区别；否则有值得看看排查。

嗯嗯，好的，谢谢
