### ISSUE TITLE
支持CompletableFuture运行多个Action

### ISSUE THREAD

**Issue by huhaosumail** [foldright/cffu#50]
目前`CompletableFuture`提供的都是最多两个入参的方法。

```java
CompletableFuture<Map> future1 = CompletableFuture.supplyAsync(() -> {
    Map result = Maps.newHashMap();
    result.put("j", "j");
    return result;
});

future1.thenAccept((Map map) -> {
    System.out.println("thenAccept:" + map.get("j"));
});

future1.thenCombine(CompletableFuture.completedFuture("123"), (map, s) -> {
    System.out.println("thenCombine:" + map.get("j"));
    System.out.println(s);
    return "yy";
});
```

-----

能否提供操作多个入参的工具类方法？
例如多个入参的消费`accept`/`combine`。

**Comment by oldratlee** [comment]
> 能否提供操作多个入参的工具类方法？

目前（[`v1.0.0-Alpha7`](https://github.com/foldright/cffu/releases/tag/v1.0.0-Alpha7)）实现了的方法，如`allResultsOf`、`mostResultsOfSuccess`，支持多个输入并有多个输入的结果。

但这些方法，输入的类型是`CompletionStage`，而不是`action`类型（如`Runnable`、`Consumer`、`Function`），对于业务使用并不常见、方便直接。

在实现了这些方法后，我现在也觉得实现你说的这样方法是有必要的。

这个功能下一个版本的高重要的功能 ❤️  @huhaosumail

**Comment by oldratlee** [comment]
@huhaosumail 在[v1.0.0-Alpha10](https://github.com/foldright/cffu/releases/tag/v1.0.0-Alpha10)版本中，实现了一部分方法：

> - implement the `multi-actions` methods in `CompletableFutureUtils` ✨ 🚀
>   - `mRunAsync`/`mRunFastFailAsync`
>   - `mSupplyAsync`/`mSupplyFastFailAsync`/`mSupplyMostSuccessAsync`
>   - `thenMRunAsync`/`thenMRunFastFailAsync`
>   - `thenMAcceptAsync`/`thenMAcceptFastFailAsync`
>   - `thenMApplyAsync`/`thenMApplyFastFailAsync`/`thenMApplyMostSuccessAsync`

还要实现相应的方法：

- `tupleOf*`方法
- `Cffu`类/`Kotlin Extension`对应的方法
